# Generated by Django 4.1.7 on 2023-03-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about-academy/')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Comand_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Info_about_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players-phot/')),
                ('number', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('games_played', models.IntegerField()),
                ('minuts_played', models.IntegerField()),
                ('start', models.IntegerField()),
                ('sub_off', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('first_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='main.commant')),
                ('second_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='main.commant')),
            ],
        ),
        migrations.CreateModel(
            name='Media_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media_logo/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Other_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('photo_T_short', models.ImageField(blank=True, null=True, upload_to='T-short/')),
                ('purchase', models.ImageField(blank=True, null=True, upload_to='purchase/')),
                ('cup', models.ImageField(blank=True, null=True, upload_to='cup/')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commant')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_number', models.CharField(max_length=255)),
                ('first_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstComands', to='main.commant')),
                ('second_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab', to='main.commant')),
            ],
        ),
        migrations.CreateModel(
            name='Team_jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_the_form', models.ImageField(blank=True, null=True, upload_to='')),
                ('other_forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.other_forms')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match_time')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(upload_to='files/%Y/%m/%d')),
                ('date', models.CharField(max_length=255)),
                ('what_account', models.CharField(max_length=255)),
                ('first_command_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstComand', to='main.commant')),
                ('second_command_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='main.commant')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.media')),
            ],
        ),
    ]
