# Generated by Django 4.1.7 on 2023-03-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_form', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Social_media/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Info_about_player',
            new_name='Player',
        ),
        migrations.DeleteModel(
            name='Main_page',
        ),
        migrations.DeleteModel(
            name='Media_url',
        ),
        migrations.RemoveField(
            model_name='info',
            name='media',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='team_jersey',
            name='other_forms',
        ),
        migrations.AddField(
            model_name='commant',
            name='player',
            field=models.ManyToManyField(to='main.player'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_banner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team_jersey',
            name='is_T_short',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team_jersey',
            name='is_cap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team_jersey',
            name='is_cup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Command/'),
        ),
        migrations.AlterField(
            model_name='match_time',
            name='first_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='match_time',
            name='second_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='first_command_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='media',
            name='second_command_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='first_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teames1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='second_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teames2', to='main.commant'),
        ),
        migrations.DeleteModel(
            name='Other_forms',
        ),
    ]
