# Generated by Django 4.1.7 on 2023-03-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_time',
            name='first_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='match_time',
            name='second_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='media',
            name='first_command_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='media',
            name='second_command_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='first_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teames1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='second_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teames2', to='main.commant'),
        ),
    ]
