# Generated by Django 4.1.7 on 2023-03-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_social_media_rename_info_about_player_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='add_form',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='team_jersey',
            name='is_T_short',
        ),
        migrations.RemoveField(
            model_name='team_jersey',
            name='is_cap',
        ),
        migrations.RemoveField(
            model_name='team_jersey',
            name='is_cup',
        ),
        migrations.AddField(
            model_name='team_jersey',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
