# Generated by Django 4.1.7 on 2023-03-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_match_time_first_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_pagea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('match_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match_time')),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Social_media/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Main_page',
        ),
        migrations.DeleteModel(
            name='Media_url',
        ),
    ]
