# Generated by Django 4.1.7 on 2023-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_add_form_shop_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img_file',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
