# Generated by Django 4.1.7 on 2023-03-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_pagea_social_media_delete_main_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='media',
        ),
    ]
