# Generated by Django 4.1.7 on 2023-03-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_info_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_pagea',
            name='match_time',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='quarter',
        ),
    ]
