# Generated by Django 4.1.7 on 2023-03-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shop_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
